import {
	cv,
	ds,
	aiengineer,
	airesearcher,
	javascript,
	typescript,
	html,
	css,
	reactjs,
	redux,
	tailwind,
	nodejs,
	mongodb,
	git,
	figma,
	docker,
	carrent,
	jobit,
	tripguide,
	threejs,
	craftwork,
	unt,
	kryptonite,
	bluerivertech,
	continental,
} from "../assets";

export const navLinks = [
	{
		id: "about",
		title: "About",
	},
	{
		id: "work",
		title: "Work",
	},
	{
		id: "contact",
		title: "Contact",
	},
];

const services = [
	{
		title: "AI/ML Engineer",
		icon: aiengineer,
	},
	{
		title: "Computer Vision Developer",
		icon: cv,
	},
	{
		title: "Data Scientist",
		icon: ds,
	},
	{
		title: "AI/ML Researcher",
		icon: airesearcher,
	},
];

const technologies = [
	{
		name: "HTML 5",
		icon: html,
	},
	{
		name: "CSS 3",
		icon: css,
	},
	{
		name: "JavaScript",
		icon: javascript,
	},
	{
		name: "TypeScript",
		icon: typescript,
	},
	{
		name: "React JS",
		icon: reactjs,
	},
	{
		name: "Redux Toolkit",
		icon: redux,
	},
	{
		name: "Tailwind CSS",
		icon: tailwind,
	},
	{
		name: "Node JS",
		icon: nodejs,
	},
	{
		name: "MongoDB",
		icon: mongodb,
	},
	{
		name: "Three JS",
		icon: threejs,
	},
	{
		name: "git",
		icon: git,
	},
	{
		name: "figma",
		icon: figma,
	},
	{
		name: "docker",
		icon: docker,
	},
];

const experiences = [
	{
		title: "Computer Vision/Artificial Intelligence Engineer",
		company_name: "Craftwork",
		icon: craftwork,
		iconBg: "#32213B",
		date: "June 2023 - Present",
		points: [
			"Combined the Grounding DINO and Segment Anything methodologies to implement natural-language-based object detection and segmentation, contributing to a $4M funding achievement and the launch of the company as a YCombinator startup.",
			"Utilized Augmented Reality to implement room size estimation, leading to an additional $2M in funding acquisition.",
			"Engineered Ruby on Rails workflow for automatic Slack notifications delivering project summaries generated by an LLM to simplify and optimize estimate creation process.",
			"Worked on boosting sales team efficiency by 30%, integrating GPT 3.5 along with RAG, prompt chaining, and function calling into workflows with automated customer responses and extraction of relevant details for project estimates, using LangChain and tracking metrics and human feedback via LangSmith.",
		],
	},
	{
		title: "Graduate Researcher",
		company_name: "University of North Texas",
		icon: unt,
		iconBg: "#FFFFFF",
		date: "August 2022 - May 2023",
		points: [
			"Re-implemented Parti and utilized a vision transformer to train an end-to-end brain-wave-based deep image reconstruction model, using Pytorch.",
			"Published the Map Estimation with Deep Dual Path Autoencoders and Skip Connection Learning paper at the flagship IEEE PIMRC conference.",
		],
	},
	{
		title: "Computer Vision/Machine Learning Researcher & Developer",
		company_name: "Blue River Technology",
		icon: bluerivertech,
		iconBg: "#FFFFFF",
		date: "May 2022 - August 2022",
		points: [
			"Conducted industrial AI research (paper reading, model selection, hyperparameter tuning, image augmentation) to generate an accurate weed/crop image segmentation model, using PyTorch and Kubeflow.",
			"Proposed and implemented knowledge distillation which increased original production model accuracy by 2%.",
			"Exceeded original production model performance by implementing a transformer model that has been selected as the company's new state-of-the-art production model (6% mAP improvement that results in $46 million of herbicide savings in Iowa fields alone).",
		],
	},
	{
		title: "Machine Learning Specialist",
		company_name: "Kryptonite",
		icon: kryptonite,
		iconBg: "#FFFFFF",
		date: "August 2020 - August 2021",
		points: [
			"Trained and deployed multi-headed sex & language audio classifier with shared backbone, using Keras and TensorFlow Serving.",
			"Utilized OpenCV to develop a computer-vision-based algorithm for multi-camera person re-identification when performing person detection and classification, boosting algorithm speed and thus decreasing GPU costs by $1M.",
			"Analyzed and employed unsupervised/self-supervised training approaches (such as SwAV and SimCLR) for representation learning to build an image retrieval system and improve model performance by 4%, using a 50 million image dataset collected from Instagram.",
			"Introduced, designed, and optimized a quickly retrainable few-shot object detection algorithm for tractor bucket teeth counting to prevent crusher gear damage, saving millions of dollars in potential economic and productivity losses.",
		],
	},
	{
		title: "Full-Stack Software Engineer",
		company_name: "Continental",
		icon: continental,
		iconBg: "#FEA501",
		date: "May 2019 - August 2019",
		points: [
			"Automated repetitive Windows tasks with PowerShell.",
			"Developed and launched an internal task management system utilizing PHP and MySQL.",
			"Designed a front-end interface for the task monitoring system, employing Vue.JS, HTML, and CSS.",
		],
	},
];

const testimonials = [
	{
		testimonial: "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
		name: "Sara Lee",
		designation: "CFO",
		company: "Acme Co",
		image: "https://randomuser.me/api/portraits/women/4.jpg",
	},
	{
		testimonial: "I've never met a web developer who truly cares about their clients' success like Rick does.",
		name: "Chris Brown",
		designation: "COO",
		company: "DEF Corp",
		image: "https://randomuser.me/api/portraits/men/5.jpg",
	},
	{
		testimonial: "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
		name: "Lisa Wang",
		designation: "CTO",
		company: "456 Enterprises",
		image: "https://randomuser.me/api/portraits/women/6.jpg",
	},
];

const projects = [
	{
		name: "Car Rent",
		description:
			"Web-based platform that allows users to search, book, and manage car rentals from various providers, providing a convenient and efficient solution for transportation needs.",
		tags: [
			{
				name: "react",
				color: "blue-text-gradient",
			},
			{
				name: "mongodb",
				color: "green-text-gradient",
			},
			{
				name: "tailwind",
				color: "pink-text-gradient",
			},
		],
		image: carrent,
		source_code_link: "https://github.com/",
	},
	{
		name: "Job IT",
		description:
			"Web application that enables users to search for job openings, view estimated salary ranges for positions, and locate available jobs based on their current location.",
		tags: [
			{
				name: "react",
				color: "blue-text-gradient",
			},
			{
				name: "restapi",
				color: "green-text-gradient",
			},
			{
				name: "scss",
				color: "pink-text-gradient",
			},
		],
		image: jobit,
		source_code_link: "https://github.com/",
	},
	{
		name: "Trip Guide",
		description:
			"A comprehensive travel booking platform that allows users to book flights, hotels, and rental cars, and offers curated recommendations for popular destinations.",
		tags: [
			{
				name: "nextjs",
				color: "blue-text-gradient",
			},
			{
				name: "supabase",
				color: "green-text-gradient",
			},
			{
				name: "css",
				color: "pink-text-gradient",
			},
		],
		image: tripguide,
		source_code_link: "https://github.com/",
	},
];

export { services, technologies, experiences, testimonials, projects };
